// Generated by scripts/generate-api-types.mjs from schemas/site-v2.schema.json.
export type Digest = string;
export type ObjectDescriptor = { "sha256": Digest; "bytes": number; "kind": "record" | "evidence" };
export type ExportManifest = { "schema": 2; "format": "site-v2"; "reportId": Digest; "sourceReportSha256": Digest; "sourceSealSha256": Digest; "exporter": string; "verification": "source-recomputed"; "objects": Array<ObjectDescriptor> };
export type ExportReference = { "sha256": Digest; "manifest": ExportManifest };
export type CompletedJob = { "schema": 2; "session": string; "machine": string; "corpus": string; "attempt": string; "plan": Digest; "configuredHarnessPin": string; "parentBundleSha256": Digest; "status": "completed"; "exports": Array<ExportReference> };
export type ProducerSummary = { [key: string]: unknown };
export type ResultData = { "reportId": Digest; "environmentId": Digest; "configurationId": Digest; "runtime": string; "contractId": Digest; "workload": string; "scenario": string; "profile": string; "metric": string; "statistic": string; "created": string; "analysisVersion": string; "summary": ProducerSummary; "evidence": Array<Digest> | null; "trackId": Digest; "metricDefinitionId": Digest; "metricDefinitionStatus": "available" | "unregistered" };
export type WireRecord = { "kind": "result" | "report" | "environment" | "configuration" | "workload" | "metric" | "artifact" | "track"; "id": Digest; "data": { [key: string]: unknown } };
export type RecordPage = { "revision": Digest; "items": Array<WireRecord>; "nextCursor": string; "complete": boolean; "total": number };
export type DatasetManifest = { "schema": 2; "revision": string; "selectionAliases": { [key: string]: string }; "limits": { [key: string]: number }; "endpoints": Array<string> };
export type ExactInteger = number | string;
