(component
  (component $provider (type $record (record (field "small" u32) (field "wide" u64)))
 (type $tuple (tuple u8 u64 bool)) (type $optional (option u64))
 (type $flags (flags "read" "write" "execute"))
   (export $record-public "record-type" (type $record)) (export $tuple-public "tuple-type" (type $tuple)) (export $optional-public "optional-type" (type $optional)) (export $flags-public "flags-type" (type $flags))
   (core module $m (func (export "record") (param i32 i64) (result i64) (i64.add (i64.mul (i64.extend_i32_u (local.get 0)) (i64.const 5)) (local.get 1)))
(func (export "tuple") (param i32 i64 i32) (result i64) (i64.add (i64.add (i64.extend_i32_u (local.get 0)) (i64.mul (local.get 1) (i64.const 2))) (i64.mul (i64.extend_i32_u (local.get 2)) (i64.const 13))))
(func (export "optional") (param i32 i64) (result i64) (if (result i64) (local.get 0) (then (local.get 1)) (else (i64.const 17))))
(func (export "flags") (param i32) (result i64) (i64.extend_i32_u (i32.add (i32.add (select (i32.const 2) (i32.const 0) (i32.and (local.get 0) (i32.const 1))) (select (i32.const 5) (i32.const 0) (i32.and (local.get 0) (i32.const 2)))) (select (i32.const 11) (i32.const 0) (i32.and (local.get 0) (i32.const 4)))))))
   (core instance $m (instantiate $m))
   (func (export "record") (param "value" $record-public) (result u64) (canon lift (core func $m "record")))
(func (export "tuple") (param "value" $tuple-public) (result u64) (canon lift (core func $m "tuple")))
(func (export "optional") (param "value" $optional-public) (result u64) (canon lift (core func $m "optional")))
(func (export "flags") (param "value" $flags-public) (result u64) (canon lift (core func $m "flags"))))
  (instance $p (instantiate $provider))
  (alias export $p "record-type" (type $record)) (alias export $p "tuple-type" (type $tuple)) (alias export $p "optional-type" (type $optional)) (alias export $p "flags-type" (type $flags))
  (alias export $p "record" (func $record))
(alias export $p "tuple" (func $tuple))
(alias export $p "optional" (func $optional))
(alias export $p "flags" (func $flags))
  (component $consumer (type $record (record (field "small" u32) (field "wide" u64)))
 (type $tuple (tuple u8 u64 bool)) (type $optional (option u64))
 (type $flags (flags "read" "write" "execute"))
   (import "record-type" (type $record-public (eq $record))) (import "tuple-type" (type $tuple-public (eq $tuple))) (import "optional-type" (type $optional-public (eq $optional))) (import "flags-type" (type $flags-public (eq $flags)))
   (import "record" (func $record (param "value" $record-public) (result u64)))
   (core func $record (canon lower (func $record)))
(import "tuple" (func $tuple (param "value" $tuple-public) (result u64)))
   (core func $tuple (canon lower (func $tuple)))
(import "optional" (func $optional (param "value" $optional-public) (result u64)))
   (core func $optional (canon lower (func $optional)))
(import "flags" (func $flags (param "value" $flags-public) (result u64)))
   (core func $flags (canon lower (func $flags)))
   (core instance $imports (export "record" (func $record)) (export "tuple" (func $tuple)) (export "optional" (func $optional)) (export "flags" (func $flags)))
   (core module $bench
    (import "ops" "record" (func $record (param i32 i64) (result i64)))
(import "ops" "tuple" (func $tuple (param i32 i64 i32) (result i64)))
(import "ops" "optional" (func $optional (param i32 i64) (result i64)))
(import "ops" "flags" (func $flags (param i32) (result i64)))

 (func (export "record-fields") (param $n i64) (result i64)
  (local $i i64) (local $sum i64)
  (block $done (loop $loop
   (br_if $done (i64.ge_u (local.get $i) (local.get $n)))
   (local.set $sum (i64.add (local.get $sum) (call $record (i32.wrap_i64 (local.get $i)) (i64.add (local.get $i) (i64.const 11)))))
   (local.set $i (i64.add (local.get $i) (i64.const 1))) (br $loop))) (local.get $sum))

 (func (export "tuple-mixed-width") (param $n i64) (result i64)
  (local $i i64) (local $sum i64)
  (block $done (loop $loop
   (br_if $done (i64.ge_u (local.get $i) (local.get $n)))
   (local.set $sum (i64.add (local.get $sum) (call $tuple (i32.and (i32.wrap_i64 (local.get $i)) (i32.const 255)) (local.get $i) (i32.and (i32.wrap_i64 (local.get $i)) (i32.const 1)))))
   (local.set $i (i64.add (local.get $i) (i64.const 1))) (br $loop))) (local.get $sum))

 (func (export "option-presence") (param $n i64) (result i64)
  (local $i i64) (local $sum i64)
  (block $done (loop $loop
   (br_if $done (i64.ge_u (local.get $i) (local.get $n)))
   (local.set $sum (i64.add (local.get $sum) (call $optional (i32.and (i32.wrap_i64 (local.get $i)) (i32.const 1)) (i64.mul (local.get $i) (i64.const 9)))))
   (local.set $i (i64.add (local.get $i) (i64.const 1))) (br $loop))) (local.get $sum))

 (func (export "flags-weighted") (param $n i64) (result i64)
  (local $i i64) (local $sum i64)
  (block $done (loop $loop
   (br_if $done (i64.ge_u (local.get $i) (local.get $n)))
   (local.set $sum (i64.add (local.get $sum) (call $flags (i32.and (i32.wrap_i64 (local.get $i)) (i32.const 7)))))
   (local.set $i (i64.add (local.get $i) (i64.const 1))) (br $loop))) (local.get $sum)))
   (core instance $b (instantiate $bench (with "ops" (instance $imports))))
   (func (export "record-fields") (param "count" u64) (result u64) (canon lift (core func $b "record-fields")))
(func (export "tuple-mixed-width") (param "count" u64) (result u64) (canon lift (core func $b "tuple-mixed-width")))
(func (export "option-presence") (param "count" u64) (result u64) (canon lift (core func $b "option-presence")))
(func (export "flags-weighted") (param "count" u64) (result u64) (canon lift (core func $b "flags-weighted"))))
  (instance $c (instantiate $consumer (with "record-type" (type $record)) (with "tuple-type" (type $tuple)) (with "optional-type" (type $optional)) (with "flags-type" (type $flags)) (with "record" (func $record)) (with "tuple" (func $tuple)) (with "optional" (func $optional)) (with "flags" (func $flags))))
  (alias export $c "record-fields" (func $record-fields)) (export "record-fields" (func $record-fields))
(alias export $c "tuple-mixed-width" (func $tuple-mixed-width)) (export "tuple-mixed-width" (func $tuple-mixed-width))
(alias export $c "option-presence" (func $option-presence)) (export "option-presence" (func $option-presence))
(alias export $c "flags-weighted" (func $flags-weighted)) (export "flags-weighted" (func $flags-weighted)))
