(module
  (type $unary (func (param i32) (result i32)))
  (type $binary (func (param i32 i32) (result i32)))
  (table 11 funcref)
  (elem (i32.const 0) $add $triple $xor $square $min $max $letter $digit $space $tree-add $tree-xor)
  (func $add (type $unary) (param $x i32) (result i32) (i32.add (local.get $x) (i32.const 7)))
  (func $triple (type $unary) (param $x i32) (result i32) (i32.mul (local.get $x) (i32.const 3)))
  (func $xor (type $unary) (param $x i32) (result i32) (i32.xor (local.get $x) (i32.const 85)))
  (func $square (type $unary) (param $x i32) (result i32) (i32.add (i32.mul (local.get $x) (local.get $x)) (i32.const 1)))
  (func $min (type $binary) (param $a i32) (param $b i32) (result i32)
    (select (local.get $a) (local.get $b) (i32.lt_u (local.get $a) (local.get $b))))
  (func $max (type $binary) (param $a i32) (param $b i32) (result i32)
    (select (local.get $a) (local.get $b) (i32.gt_u (local.get $a) (local.get $b))))
  (func $letter (type $unary) (param $s i32) (result i32)
    (i32.add (i32.const 1) (i32.shl (i32.eqz (local.get $s)) (i32.const 2))))
  (func $digit (type $unary) (param $s i32) (result i32)
    (i32.add (i32.const 2) (i32.shl (i32.eqz (local.get $s)) (i32.const 2))))
  (func $space (type $unary) (param i32) (result i32) (i32.const 0))
  (func $tree-add (type $binary) (param $depth i32) (param $seed i32) (result i32)
    (if (result i32) (i32.eqz (local.get $depth))
      (then (i32.and (local.get $seed) (i32.const 255)))
      (else (i32.add
        (call_indirect (type $binary) (i32.sub (local.get $depth) (i32.const 1))
          (i32.add (local.get $seed) (i32.const 1)) (i32.add (i32.const 9) (i32.and (local.get $seed) (i32.const 1))))
        (call_indirect (type $binary) (i32.sub (local.get $depth) (i32.const 1))
          (i32.add (local.get $seed) (i32.const 3)) (i32.add (i32.const 9) (i32.and (i32.shr_u (local.get $seed) (i32.const 1)) (i32.const 1))))))))
  (func $tree-xor (type $binary) (param $depth i32) (param $seed i32) (result i32)
    (if (result i32) (i32.eqz (local.get $depth))
      (then (i32.xor (i32.and (local.get $seed) (i32.const 255)) (i32.const 90)))
      (else (i32.xor
        (call_indirect (type $binary) (i32.sub (local.get $depth) (i32.const 1))
          (i32.add (local.get $seed) (i32.const 2)) (i32.add (i32.const 9) (i32.and (local.get $seed) (i32.const 1))))
        (call_indirect (type $binary) (i32.sub (local.get $depth) (i32.const 1))
          (i32.add (local.get $seed) (i32.const 5)) (i32.add (i32.const 9) (i32.and (i32.shr_u (local.get $seed) (i32.const 1)) (i32.const 1))))))))

  (func (export "indirect-composition") (param $n i32) (result i32)
    (local $i i32) (local $total i32) (local $state i32)
    (block $done (loop $next
      (br_if $done (i32.ge_u (local.get $i) (local.get $n)))
      (local.set $total (i32.add (local.get $total) (block (result i32)
    (local.set $state (i32.and (call_indirect (type $unary)
      (local.get $state) (i32.and (local.get $i) (i32.const 3))) (i32.const 4095)))
    (local.get $state))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $next)))
    (local.get $total))

  (func (export "indirect-sorting-network") (param $n i32) (result i32)
    (local $i i32) (local $total i32) (local $a i32) (local $b i32) (local $c i32) (local $d i32) (local $slot i32) (local $tmp i32)
    (block $done (loop $next
      (br_if $done (i32.ge_u (local.get $i) (local.get $n)))
      (local.set $total (i32.add (local.get $total) (block (result i32)
    (local.set $a (i32.and (i32.add (i32.mul (local.get $i) (i32.const 37)) (i32.const 11)) (i32.const 255)))
    (local.set $b (i32.and (i32.add (i32.mul (local.get $i) (i32.const 19)) (i32.const 7)) (i32.const 255)))
    (local.set $c (i32.and (i32.add (i32.mul (local.get $i) (i32.const 13)) (i32.const 101)) (i32.const 255)))
    (local.set $d (i32.and (i32.add (i32.mul (local.get $i) (i32.const 29)) (i32.const 53)) (i32.const 255)))
    (local.set $slot (i32.add (i32.const 4) (i32.and (local.get $i) (i32.const 1))))

  (local.set $tmp (call_indirect (type $binary)
    (local.get $a) (local.get $b) (local.get $slot)))
  (local.set $b (call_indirect (type $binary)
    (local.get $a) (local.get $b) (i32.xor (local.get $slot) (i32.const 1))))
  (local.set $a (local.get $tmp))
  (local.set $tmp (call_indirect (type $binary)
    (local.get $c) (local.get $d) (local.get $slot)))
  (local.set $d (call_indirect (type $binary)
    (local.get $c) (local.get $d) (i32.xor (local.get $slot) (i32.const 1))))
  (local.set $c (local.get $tmp))
  (local.set $tmp (call_indirect (type $binary)
    (local.get $a) (local.get $c) (local.get $slot)))
  (local.set $c (call_indirect (type $binary)
    (local.get $a) (local.get $c) (i32.xor (local.get $slot) (i32.const 1))))
  (local.set $a (local.get $tmp))
  (local.set $tmp (call_indirect (type $binary)
    (local.get $b) (local.get $d) (local.get $slot)))
  (local.set $d (call_indirect (type $binary)
    (local.get $b) (local.get $d) (i32.xor (local.get $slot) (i32.const 1))))
  (local.set $b (local.get $tmp))
  (local.set $tmp (call_indirect (type $binary)
    (local.get $b) (local.get $c) (local.get $slot)))
  (local.set $c (call_indirect (type $binary)
    (local.get $b) (local.get $c) (i32.xor (local.get $slot) (i32.const 1))))
  (local.set $b (local.get $tmp))
    (i32.add (i32.add (local.get $a) (i32.mul (local.get $b) (i32.const 3)))
      (i32.add (i32.mul (local.get $c) (i32.const 5)) (i32.mul (local.get $d) (i32.const 7)))))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $next)))
    (local.get $total))

  (func (export "indirect-token-recognition") (param $n i32) (result i32)
    (local $i i32) (local $total i32) (local $state i32) (local $packed i32)
    (block $done (loop $next
      (br_if $done (i32.ge_u (local.get $i) (local.get $n)))
      (local.set $total (i32.add (local.get $total) (block (result i32)
    (local.set $packed (call_indirect (type $unary) (local.get $state)
      (i32.add (i32.const 6) (i32.rem_u (i32.add (i32.mul (local.get $i) (i32.const 5))
        (i32.div_u (local.get $i) (i32.const 7))) (i32.const 3)))))
    (local.set $state (i32.and (local.get $packed) (i32.const 3)))
    (i32.shr_u (local.get $packed) (i32.const 2)))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $next)))
    (local.get $total))

  (func (export "indirect-tree-fold") (param $n i32) (result i32)
    (local $i i32) (local $total i32)
    (block $done (loop $next
      (br_if $done (i32.ge_u (local.get $i) (local.get $n)))
      (local.set $total (i32.add (local.get $total) (call_indirect (type $binary)
    (i32.add (i32.rem_u (local.get $i) (i32.const 5)) (i32.const 1))
    (local.get $i) (i32.add (i32.const 9) (i32.and (local.get $i) (i32.const 1))))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $next)))
    (local.get $total))
)
