(module
  (func $euclid (param $a i32) (param $b i32) (result i32 i32)
    (local $steps i32) (local $r i32)
    (block $done (loop $next
      (br_if $done (i32.eqz (local.get $b)))
      (local.set $r (i32.rem_u (local.get $a) (local.get $b)))
      (local.set $a (local.get $b)) (local.set $b (local.get $r))
      (local.set $steps (i32.add (local.get $steps) (i32.const 1)))
      (br $next)))
    (local.get $a) (local.get $steps))
  (func $fib (param $k i32) (result i32 i32)
    (local $a i32) (local $b i32)
    (local.get $k) (i32.const 0) (i32.const 1)
    (loop $next (param i32 i32 i32) (result i32 i32)
      (local.set $b) (local.set $a) (local.set $k)
      (if (result i32 i32) (i32.eqz (local.get $k))
        (then (local.get $a) (local.get $b))
        (else (br $next (i32.sub (local.get $k) (i32.const 1))
          (local.get $b) (i32.add (local.get $a) (local.get $b)))))))
  (func $ordered (param $a i32) (param $b i32) (result i32 i32)
    (if (result i32 i32) (i32.le_u (local.get $a) (local.get $b))
      (then (local.get $a) (local.get $b))
      (else (local.get $b) (local.get $a))))
  (func $sqrt-rem (param $x i32) (result i32 i32)
    (local $root i32) (local $odd i32)
    (local.set $odd (i32.const 1))
    (block $done (loop $next
      (br_if $done (i32.lt_u (local.get $x) (local.get $odd)))
      (local.set $x (i32.sub (local.get $x) (local.get $odd)))
      (local.set $odd (i32.add (local.get $odd) (i32.const 2)))
      (local.set $root (i32.add (local.get $root) (i32.const 1)))
      (br $next)))
    (local.get $root) (local.get $x))

  (func (export "euclid-result-and-steps") (param $n i32) (result i32)
    (local $i i32) (local $total i32) (local $gcd i32) (local $steps i32)
    (block $done (loop $next
      (br_if $done (i32.ge_u (local.get $i) (local.get $n)))
      (local.set $total (i32.add (local.get $total) (block (result i32)
    (call $euclid (i32.add (i32.mul (local.get $i) (i32.const 29)) (i32.const 7))
      (i32.add (i32.rem_u (local.get $i) (i32.const 17)) (i32.const 2)))
    (local.set $steps) (local.set $gcd)
    (i32.add (i32.mul (local.get $gcd) (i32.const 17)) (local.get $steps)))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $next)))
    (local.get $total))

  (func (export "fibonacci-loop-tuple") (param $n i32) (result i32)
    (local $i i32) (local $total i32)
    (block $done (loop $next
      (br_if $done (i32.ge_u (local.get $i) (local.get $n)))
      (local.set $total (i32.add (local.get $total) (block (result i32)
    (call $fib (i32.add (i32.rem_u (local.get $i) (i32.const 20)) (i32.const 1)))
    (i32.xor))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $next)))
    (local.get $total))

  (func (export "conditional-order-pair") (param $n i32) (result i32)
    (local $i i32) (local $total i32) (local $lo i32) (local $hi i32)
    (block $done (loop $next
      (br_if $done (i32.ge_u (local.get $i) (local.get $n)))
      (local.set $total (i32.add (local.get $total) (block (result i32)
    (call $ordered (i32.and (i32.add (i32.mul (local.get $i) (i32.const 37)) (i32.const 11)) (i32.const 255))
      (i32.and (i32.add (i32.mul (local.get $i) (i32.const 19)) (i32.const 7)) (i32.const 255)))
    (local.set $hi) (local.set $lo)
    (i32.add (i32.mul (local.get $lo) (i32.const 3)) (i32.sub (local.get $hi) (local.get $lo))))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $next)))
    (local.get $total))

  (func (export "integer-sqrt-remainder") (param $n i32) (result i32)
    (local $i i32) (local $total i32) (local $root i32) (local $remainder i32)
    (block $done (loop $next
      (br_if $done (i32.ge_u (local.get $i) (local.get $n)))
      (local.set $total (i32.add (local.get $total) (block (result i32)
    (call $sqrt-rem (i32.and (i32.add (i32.mul (local.get $i) (i32.const 43)) (i32.const 19)) (i32.const 4095)))
    (local.set $remainder) (local.set $root)
    (i32.add (i32.mul (local.get $root) (i32.const 17)) (local.get $remainder)))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $next)))
    (local.get $total))
)
