(module
 (type $t (func (param i32) (result i32)))
 (table $t0 16 16 funcref) (table $t1 16 16 funcref) (table $sparse 16 16 funcref)
 (elem declare func $inc $double)
 (func $inc (type $t) (param i32) (result i32) (i32.add (local.get 0) (i32.const 1)))
 (func $double (type $t) (param i32) (result i32) (i32.mul (local.get 0) (i32.const 2)))
 (func (export "initialize")
  (table.fill $t0 (i32.const 0) (ref.func $inc) (i32.const 16))
  (table.fill $t1 (i32.const 0) (ref.func $double) (i32.const 16)))
 (func (export "sparse-reference-compaction") (param $n i32) (result i32)
  (local $i i32) (local $j i32) (local $write i32) (local $k i32) (local $sum i32) (local $r funcref)
  (block $done (loop $round (br_if $done (i32.ge_u (local.get $i) (local.get $n)))
   (local.set $j (i32.const 0))
   (loop $seed
    (local.set $k (i32.add (local.get $i) (local.get $j)))
    (table.set $sparse (local.get $j)
     (if (result funcref) (i32.eqz (i32.and (local.get $k) (i32.const 3))) (then (ref.null func))
      (else (if (result funcref) (i32.and (local.get $k) (i32.const 1)) (then (ref.func $inc)) (else (ref.func $double))))))
    (local.set $j (i32.add (local.get $j) (i32.const 1))) (br_if $seed (i32.lt_u (local.get $j) (i32.const 16))))
   (local.set $j (i32.const 0)) (local.set $write (i32.const 0))
   (loop $compact
    (local.set $r (table.get $sparse (local.get $j)))
    (if (i32.eqz (ref.is_null (local.get $r))) (then
     (table.set $sparse (local.get $write) (local.get $r))
     (local.set $write (i32.add (local.get $write) (i32.const 1)))))
    (local.set $j (i32.add (local.get $j) (i32.const 1))) (br_if $compact (i32.lt_u (local.get $j) (i32.const 16))))
   (table.fill $sparse (local.get $write) (ref.null func) (i32.sub (i32.const 16) (local.get $write)))
   (local.set $j (i32.const 0))
   (loop $checksum
    (local.set $sum (i32.add (local.get $sum) (call_indirect $sparse (type $t) (i32.add (local.get $i) (local.get $j)) (local.get $j))))
    (local.set $j (i32.add (local.get $j) (i32.const 1))) (br_if $checksum (i32.lt_u (local.get $j) (local.get $write))))
   (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $round))) (local.get $sum))
 (func (export "cross-table-dispatch") (param $n i32) (result i32)
  (local $i i32) (local $sum i32)
  (table.copy $t0 $t1 (i32.const 8) (i32.const 0) (i32.const 8))
  (block $done (loop $loop (br_if $done (i32.ge_u (local.get $i) (local.get $n)))
   (local.set $sum (i32.add (local.get $sum) (call_indirect $t0 (type $t) (local.get $i) (i32.and (local.get $i) (i32.const 15)))))
   (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $loop))) (local.get $sum)))
