(module
  (func $even (param $k i32) (result i32)
    (if (result i32) (i32.eqz (local.get $k))
      (then (i32.const 1))
      (else (return_call $odd (i32.sub (local.get $k) (i32.const 1))))))
  (func $odd (param $k i32) (result i32)
    (if (result i32) (i32.eqz (local.get $k))
      (then (i32.const 0))
      (else (return_call $even (i32.sub (local.get $k) (i32.const 1))))))
  (func $gcd (param $a i32) (param $b i32) (result i32)
    (if (result i32) (i32.eqz (local.get $b))
      (then (local.get $a))
      (else (return_call $gcd (local.get $b) (i32.rem_u (local.get $a) (local.get $b))))))
  (func $search (param $lo i32) (param $hi i32) (param $target i32) (result i32)
    (local $mid i32) (local $value i32)
    (if (i32.ge_u (local.get $lo) (local.get $hi)) (then (return (i32.const 0))))
    (local.set $mid (i32.shr_u (i32.add (local.get $lo) (local.get $hi)) (i32.const 1)))
    (local.set $value (i32.add (i32.mul (local.get $mid) (i32.const 3)) (i32.const 2)))
    (if (i32.eq (local.get $value) (local.get $target))
      (then (return (i32.add (local.get $mid) (i32.const 1)))))
    (if (result i32) (i32.lt_u (local.get $value) (local.get $target))
      (then (return_call $search (i32.add (local.get $mid) (i32.const 1)) (local.get $hi) (local.get $target)))
      (else (return_call $search (local.get $lo) (local.get $mid) (local.get $target)))))
  (func $digits (param $value i32) (param $total i32) (result i32)
    (if (result i32) (i32.eqz (local.get $value))
      (then (local.get $total))
      (else (return_call $digits (i32.div_u (local.get $value) (i32.const 10))
        (i32.add (local.get $total) (i32.rem_u (local.get $value) (i32.const 10)))))))

  (func (export "mutual-parity-count") (param $n i32) (result i32)
    (local $i i32) (local $total i32)
    (block $done (loop $next
      (br_if $done (i32.ge_u (local.get $i) (local.get $n)))
      (local.set $total (i32.add (local.get $total) (call $even (i32.add (i32.rem_u (local.get $i) (i32.const 31)) (i32.const 1)))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $next)))
    (local.get $total))

  (func (export "euclidean-gcd") (param $n i32) (result i32)
    (local $i i32) (local $total i32)
    (block $done (loop $next
      (br_if $done (i32.ge_u (local.get $i) (local.get $n)))
      (local.set $total (i32.add (local.get $total) (call $gcd (i32.add (i32.mul (local.get $i) (i32.const 13)) (i32.const 17))
    (i32.add (i32.rem_u (local.get $i) (i32.const 17)) (i32.const 1)))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $next)))
    (local.get $total))

  (func (export "binary-search") (param $n i32) (result i32)
    (local $i i32) (local $total i32)
    (block $done (loop $next
      (br_if $done (i32.ge_u (local.get $i) (local.get $n)))
      (local.set $total (i32.add (local.get $total) (call $search (i32.const 0) (i32.const 128)
    (i32.rem_u (i32.add (i32.mul (local.get $i) (i32.const 11)) (i32.const 5)) (i32.const 400)))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $next)))
    (local.get $total))

  (func (export "decimal-digit-sum") (param $n i32) (result i32)
    (local $i i32) (local $total i32)
    (block $done (loop $next
      (br_if $done (i32.ge_u (local.get $i) (local.get $n)))
      (local.set $total (i32.add (local.get $total) (call $digits (i32.add (i32.mul (local.get $i) (i32.const 997)) (i32.const 12345)) (i32.const 0))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $next)))
    (local.get $total))
)
