package store

import (
	"encoding/json"
	"github.com/JairusSW/wasm.fyi/service/internal/wire"
)

type offlineMetadata struct {
	Node       bool
	Bytes      int64
	References []string
}

func (s *Store) protectOfflineInput(id string) {
	s.offlineMu.Lock()
	defer s.offlineMu.Unlock()
	if s.offline {
		s.offlineInputs[id] = true
	}
}

// Track only metadata generated by put, never producer evidence. A conservative
// JSON hash-reference walk keeps a superset of the final metadata closure.
func (s *Store) trackOfflineMetadata(id string, body []byte, value any) error {
	s.offlineMu.RLock()
	active := s.offline
	s.offlineMu.RUnlock()
	if !active {
		return nil
	}
	var decoded any
	if err := json.Unmarshal(body, &decoded); err != nil {
		return err
	}
	refs := map[string]bool{}
	var walk func(any)
	walk = func(v any) {
		switch x := v.(type) {
		case string:
			if wire.IsHash(x) {
				refs[x] = true
			}
		case []any:
			for _, e := range x {
				walk(e)
			}
		case map[string]any:
			for k, e := range x {
				walk(k)
				walk(e)
			}
		}
	}
	walk(decoded)
	_, isNode := value.(node)
	metadata := offlineMetadata{Node: isNode, Bytes: int64(len(body))}
	for ref := range refs {
		metadata.References = append(metadata.References, ref)
	}
	s.offlineMu.Lock()
	s.offlineDerived[id] = metadata
	s.offlineMu.Unlock()
	return nil
}

// Intermediate private map pages were never referenced by a published revision.
// Drop only those pages. Producer inputs, non-node metadata, and every installed
// final filename remain untouched, including pages from older revisions.
func (s *Store) pruneOfflineNodes(roots []string) error {
	if len(roots) == 0 {
		return nil
	}
	s.contentMu.Lock()
	defer s.contentMu.Unlock()
	s.offlineMu.Lock()
	defer s.offlineMu.Unlock()
	if !s.offline {
		return nil
	}
	marked := map[string]bool{}
	queue := append([]string{}, roots...)
	for len(queue) > 0 {
		id := queue[len(queue)-1]
		queue = queue[:len(queue)-1]
		if marked[id] {
			continue
		}
		marked[id] = true
		if metadata, ok := s.offlineDerived[id]; ok {
			queue = append(queue, metadata.References...)
		}
	}
	for id, metadata := range s.offlineDerived {
		path := s.offlineFiles[id]
		if !metadata.Node || marked[id] || s.offlineInputs[id] || path == "" || path == id {
			continue
		}
		if err := s.objects.Remove(path); err != nil {
			return err
		}
		delete(s.offlineFiles, id)
		delete(s.offlineDerived, id)
		delete(s.offlineInputs, id)
		s.contentBytes -= metadata.Bytes
		s.offlineDiscarded++
	}
	return nil
}

func (s *Store) OfflineDiscardedIndexPages() int64 {
	s.offlineMu.RLock()
	defer s.offlineMu.RUnlock()
	return s.offlineDiscarded
}
