name: Check website
on:
  pull_request:
  push:
    branches-ignore: [main]
permissions:
  contents: read
concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: '26.4.0'
      - uses: pnpm/action-setup@v6
      - uses: extractions/setup-just@v4
        with:
          just-version: '1.58.0'
      - run: just setup
      - run: just verify
        env:
          BASE_PATH: /wasm.fyi
      - uses: actions/upload-artifact@v7
        with:
          name: website-preview
          path: build
          retention-days: 7
